GIS_APP/GIS_APP/Models/Area.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entity
{
    [Table("tb_areas")]
    public class Area
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public long id { get; set; }
        public string name { get; set; }

        public virtual List<Position> lsPositions { get; set; }
    }
}

GIS_APP/GIS_APP/Models/MyDbContext.cs
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration.Conventions;
using System.Linq;


namespace Entity
{
    public class MyDbContext : DbContext
    {
        public MyDbContext()
            : base("name=PostgresConnection")
        {
            //Database.SetInitializer<MyDbContext>(null);
        }

        public DbSet<Position> Positions { get; set; }
        public DbSet<Point> Points { get; set; }
        public DbSet<Area> Areas { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
            modelBuilder.HasDefaultSchema("public");
            base.OnModelCreating(modelBuilder);
        }

    }
}

GIS_APP/GIS_APP/Models/Point.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entity
{
    [Table("tb_points")]
    public class Point
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public long id { get; set; }

        [Column("latitude")]
        public double lat { get; set; }

        [Column("longitude")]
        public double lng { get; set; }

        [ForeignKey("position")]
        public long pos_id { get; set; }
        public virtual Position position { get; set; }
    }
}

GIS_APP/GIS_APP/Models/Position.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entity
{
    [Table("tb_positions")]
    public class Position
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public long id { get; set; }

        [Column("latitude")]
        public double lat { get; set; }
        [Column("longitude")]
        public double lng { get; set; }

        [ForeignKey("area")]
        public long area_id { get; set; }
        public virtual Area area { get; set; }

        public virtual List<Point> lsPoints { get; set; }
    }
}

GIS_APP/GIS_APP/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GIS_APP.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Index1()
        {
            return View();
        }

        public ActionResult Index2()
        {
            return View();
        }

        public ActionResult Index3()
        {
            return View();
        }

        public ActionResult Index4()
        {
            return View();
        }
    }
}

GIS_APP/GIS_APP/Controllers/MapController.cs
using Entity;
using GIS_APP.WSHandler;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GIS_APP.Controllers
{
    public class MapController : Controller
    {
        // GET: Map
        MyDbContext context;
        public MapController()
        {
            context = new MyDbContext();
        }

        public ActionResult Index(long id = 0)
        {
            if (id == 0)
                id = 1;
            Area area = context.Areas.Where(x => x.id == id).FirstOrDefault();
            return View(area);
        }

        public ActionResult Mobile(string id)
        {
            return View();
        }

        [HttpPost]
        public JsonResult Position(string message)
        {
            dynamic obj = JsonConvert.DeserializeObject(message);
            if (obj != null && obj.type != null)
            {
                if (obj.type == "mobile" && obj.position != null)
                {
                    ServiceProcessHandler handle = new ServiceProcessHandler();
                    Position position = new Position { lat = (double)obj.position.lat, lng = (double)obj.position.lng };
                    position.lsPoints = new List<Point>();
                    if (obj.points != null)
                    {
                        position.lsPoints.Add(new Point { lat = (double)obj.points.p1.lat, lng = (double)obj.points.p1.lng });
                        position.lsPoints.Add(new Point { lat = (double)obj.points.p2.lat, lng = (double)obj.points.p2.lng });
                        position.lsPoints.Add(new Point { lat = (double)obj.points.p3.lat, lng = (double)obj.points.p3.lng });
                        position.lsPoints.Add(new Point { lat = (double)obj.points.p4.lat, lng = (double)obj.points.p4.lng });
                        //dynamic[] lsPoint = (dynamic[])obj.points;
                        //lsPoint.ToList().ForEach(x =>
                        //{
                        //    position.lsPoints.Add(new Point { lat = (double)x.lat, lng = (double)x.lng });
                        //});
                    }
                    handle.Position(position);
                }
            }
            return Json(true);
        }
    }
}

GIS_APP/GIS_APP/Views/Home/Index.cshtml
<div class="panel">
    <div class="panel-body">
        <div class="row">
            <div class="col-md-6">
                <div id="map" style="width: 100%; height: 400px;"></div>
            </div>

            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-6">
                        <label>Latitude</label>
                        <input type="number" class="form-control" placeholder="Latitude" id="latitude" />
                    </div>
                    <div class="col-md-6">
                        <label>Longitude</label>
                        <input type="number" class="form-control" placeholder="Longitude" id="longitude" />
                    </div>
                </div>
                <br />
                <a class="btn btn-success" id="add">Adicionar Ponto</a>
            </div>
        </div>
    </div>
</div>
<script>
    $(function () {
        $('#add').click(function () {
            var lat = $('#latitude').val();
            var lon = $('#longitude').val();
            Marker(lat, lon);
            $('#latitude').val(0);
            $('#longitude').val(0);
        });
    });
</script>
<script type="text/javascript">
    var locations = [
      ['Bondi Beach', -33.890542, 151.274856, 4],
      ['Coogee Beach', -33.923036, 151.259052, 5],
      ['Cronulla Beach', -34.028249, 151.157507, 3],
      ['Manly Beach', -33.80010128657071, 151.28747820854187, 2],
      ['Maroubra Beach', -33.950198, 151.259302, 1]
    ];

    var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 15,
        center: new google.maps.LatLng(-27.635424331918777, -54.13765009492636),
        mapTypeId: google.maps.MapTypeId.SATELLITE
    });

    var infowindow = new google.maps.InfoWindow();

    var marker, i;

    //for (i = 0; i < locations.length; i++) {
    //    marker = new google.maps.Marker({
    //        position: new google.maps.LatLng(locations[i][1], locations[i][2]),
    //        map: map
    //    });

    //    google.maps.event.addListener(marker, 'click', (function (marker, i) {
    //        return function () {
    //            infowindow.setContent(locations[i][0]);
    //            infowindow.open(map, marker);
    //        }
    //    })(marker, i));
    //}

    google.maps.event.addListener(map, "click", function (event) {
        var lat = event.latLng.lat();
        var lon = event.latLng.lng();
        Marker(lat, lon);
        console.log(lat + ', ' + lon);
    });

    function Marker(lat, lon) {
        marker = new google.maps.Marker({
            position: new google.maps.LatLng(lat, lon),
            map: map
        });
    }
    Marker(-27.63638431835631, -54.134238325059414);
</script>

GIS_APP/GIS_APP/Views/Home/Index1.cshtml
<div class="panel">
    <div class="panel-body">
        <div class="row">
            <div class="col-md-6">
                <div id="map" style="width: 100%; height: 400px;"></div>
            </div>

            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-6">
                        <label>Latitude</label>
                        <input type="number" class="form-control" placeholder="Latitude" id="latitude" />
                    </div>
                    <div class="col-md-6">
                        <label>Longitude</label>
                        <input type="number" class="form-control" placeholder="Longitude" id="longitude" />
                    </div>
                </div>
                <br />
                <a class="btn btn-success" id="add">Adicionar Ponto</a>
            </div>
        </div>
    </div>
</div>
<script>
    $(function () {
        $('#add').click(function () {
            var lat = $('#latitude').val();
            var lon = $('#longitude').val();
            Marker(lat, lon);
            $('#latitude').val(0);
            $('#longitude').val(0);
        });
    });
</script>
<script>
    // This example adds a user-editable rectangle to the map.
    // When the user changes the bounds of the rectangle,
    // an info window pops up displaying the new bounds.

    var rectangle;
    var map;
    var infoWindow;

    function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
            center: {lat: 44.5452, lng: -78.5389},
            zoom: 9
        });

        var bounds = {
            north: 44.599,
            south: 44.490,
            east: -78.443,
            west: -78.649
        };

        // Define the rectangle and set its editable property to true.
        rectangle = new google.maps.Rectangle({
            bounds: bounds,
            editable: true,
            draggable: true
        });

        rectangle.setMap(map);

        // Add an event listener on the rectangle.
        rectangle.addListener('bounds_changed', showNewRect);

        // Define an info window on the map.
        infoWindow = new google.maps.InfoWindow();
    }
    // Show the new coordinates for the rectangle in an info window.

    /** @this {google.maps.Rectangle} */
    function showNewRect(event) {
        var ne = rectangle.getBounds().getNorthEast();
        var sw = rectangle.getBounds().getSouthWest();

        var contentString = '<b>Rectangle moved.</b><br>' +
            'New north-east corner: ' + ne.lat() + ', ' + ne.lng() + '<br>' +
            'New south-west corner: ' + sw.lat() + ', ' + sw.lng();

        // Set the info window's content and position.
        infoWindow.setContent(contentString);
        infoWindow.setPosition(ne);

        infoWindow.open(map);
    }
    initMap();
</script>

GIS_APP/GIS_APP/Views/Home/Index2.cshtml
<div class="panel">
    <div class="panel-body">
        <div class="row">
            <div class="col-md-6">
                <div id="map" style="width: 100%; height: 400px;"></div>
            </div>

            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-6">
                        <label>Latitude</label>
                        <input type="number" class="form-control" placeholder="Latitude" id="latitude" />
                    </div>
                    <div class="col-md-6">
                        <label>Longitude</label>
                        <input type="number" class="form-control" placeholder="Longitude" id="longitude" />
                    </div>
                </div>
                <br />
                <a class="btn btn-success" id="add">Adicionar Ponto</a>
            </div>
        </div>
    </div>
</div>
<script>
    $(function () {
        $('#add').click(function () {
            var lat = $('#latitude').val();
            var lon = $('#longitude').val();
            Marker(lat, lon);
            $('#latitude').val(0);
            $('#longitude').val(0);
        });
    });
</script>
<script type="text/javascript">
    var markerArray = [];

    var directionsService = new google.maps.DirectionsService;

    var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 15,
        center: new google.maps.LatLng(-27.635424331918777, -54.13765009492636),
        mapTypeId: google.maps.MapTypeId.SATELLITE
    });


    var directionsDisplay = new google.maps.DirectionsRenderer({ map: map });


    var infowindow = new google.maps.InfoWindow();

    var marker, i;


    google.maps.event.addListener(map, "mousemove", function (event) {
        var lat = event.latLng.lat();
        var lon = event.latLng.lng();
        Marker(lat, lon);
        //console.log(lat + ', ' + lon);
    });

    function Marker(lat, lon) {
        marker = new google.maps.Marker({
            position: new google.maps.LatLng(lat, lon),
            map: map
        });
    }
    //Marker(-27.63638431835631, -54.134238325059414);


    function showSteps(directionResult, markerArray, stepDisplay, map) {
        // For each step, place a marker, and add the text to the marker's infowindow.
        // Also attach the marker to an array so we can keep track of it and remove it
        // when calculating new routes.
        var myRoute = directionResult.routes[0].legs[0];
        for (var i = 0; i < myRoute.steps.length; i++) {
            var marker = markerArray[i] = markerArray[i] || new google.maps.Marker;
            marker.setMap(map);
            marker.setPosition(myRoute.steps[i].start_location);
            attachInstructionText(
                stepDisplay, marker, myRoute.steps[i].instructions, map);
        }
    }
</script>

GIS_APP/GIS_APP/Views/Home/Index3.cshtml
<div class="panel">
    <div class="panel-body">
        <div class="row">
            <div class="col-md-8">
                <div id="map" style="width: 100%; height: 400px;"></div>
            </div>

            <div class="col-md-4">
                <div class="row">
                    <div class="col-md-2">Largura:</div>
                    <div class="col-md-3">
                        <input type="number" class="form-control" placeholder="Largura" id="largura" />
                    </div>
                    <div class="col-md-6">
                        <a class="btn btn-success" onclick="clearMarkers()">Limpar</a>
                        <a class="btn btn-success" id="stop">Parar</a>
                    </div>
                </div>
                <br />
                <div class="row">
                    @*<div class="col-md-4">
                            <input type="text" class="form-control" id="navegar" placeholder="Navegar" />
                        </div>*@
                    <div class="col-md-6">
                        <input type="number" class="form-control" id="velocidade" placeholder="Velocidade" />
                    </div>
                    <div class="col-md-6">
                        <input type="number" class="form-control" id="inclinacao" placeholder="Inclinação" />
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-md-6 col-xs-12">
                        <div id="bl">
                            <div id="block">
                                <div class="a">A</div>
                                <div class="b">B</div>
                                <div class="c">C</div>
                                <div class="d">D</div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-xs-12" style="padding: 0;">
                        <ul id="block_p" style="list-style: none; padding: 0;"></ul>
                    </div>
                    <div class="col-md-6">
                        <span id="direcoes"></span>
                    </div>
                    <style>
                        #bl {
                            width: 200px;
                            height: 200px;
                            border: 1px solid;
                            position: relative;
                            padding: 50px;
                            /*background-size: 100% 1em;
                            background-image: linear-gradient(0deg, transparent 80px, #000000 80px, #000000 80px, transparent 80px), linear-gradient(#000 0.05em, transparent .05em);*/
                        }

                        #block {
                            width: 100px;
                            height: 100px;
                            border: 1px solid;
                            transform: rotate(0deg);
                            font-weight: bold;
                        }

                            #block > div {
                                width: 1px;
                                height: 1px;
                                border: 5px solid;
                                position: absolute;
                            }

                            #block > .a {
                                left: 0;
                                top: 0;
                            }

                            #block > .b {
                                right: 0;
                                top: 0;
                            }

                            #block > .c {
                                left: 0;
                                bottom: 0;
                            }

                            #block > .d {
                                bottom: 0;
                                right: 0;
                            }
                    </style>
                    <script>
                        function margins() {
                            var _s = 10000;
                            $('#block_p').html('');
                            $('#block > div').each(function (index, item) {
                                var top = $(item).position().top;
                                top = Math.round(top * _s) / _s;
                                var left = $(item).position().left;
                                left = Math.round(left * _s) / _s;
                                var text = $(item).text();
                                var txt = text + ' = top: ' + top + ', left: ' + left;
                                $('#block_p').append($('<li>' + txt + '</li>'));
                                console.log(txt);
                            });
                            console.log('______________________________________');
                        }

                    </script>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/Content/site.js"></script>

<script type="text/javascript">
    var canMark = false;
    var dif = mtr_grau(15); //-0.000021457672119140625;
    var grau = mtr_grau(5);

    $(function () {
        addMarker(center);
        $('#largura').val(width);
        $('#velocidade').val(grau_mtr(dif));
        $('#inclinacao').val(grau_mtr(grau));
        $('#largura').change(function (event) {
            width = parseInt($(this).val());
        });
        $('#velocidade').change(function (event) {
            dif = mtr_grau(parseFloat($(this).val()));
        });
        $('#inclinacao').change(function (event) {
            var val = $(this).val();
            grau = mtr_grau(parseInt($(this).val()));
            $('#block').attr('style', 'transform: rotate(' + val + 'deg);');
            margins();
        });

        $('#stop').click(function () {
            canMark = false;
        });

    });
    $(document).on('keydown1', '#navegar, body', function (event) {//keyup keypress
        //console.log(event);
        var lat = center.lat;
        var lng = center.lng;
        switch (event.keyCode) {
            case 37:
                lng = lng - dif;
                break;
            case 38:
                lat = lat + dif;
                break;
            case 39:
                lng = lng + dif;
                break;
            case 40:
                lat = lat - dif;
                break;
        }
        center = { lat: lat, lng: lng };
        map.setCenter(center);
        addMarker(center);
    });

    map.addListener("mousemove", function (event) {
        var lat = event.latLng.lat();
        var lng = event.latLng.lng();
        var _c = { lat: lat, lng: lng };
        //addPolygon(_c);
        //if (canMark)
        //addCircle(_c);
        //addMarker({ lat: lat, lng: lng });
        //FilterList(_c);
        CalculaDistancia(last_marker, _c);
        last_marker = _c;
    });

    map.addListener("click", function (event) {
        canMark = false;//!canMark;
        var lat = event.latLng.lat();
        var lng = event.latLng.lng();
        center = { lat: lat, lng: lng };
        map.setCenter(center);
        //CalculaDistancia(last_marker, center);
        CalculaDistancia(last_marker, center);
        addPolygon(center);
        //addMarker(center);
        last_marker = center;
    });

    function CalculaDistancia(p1, p2) {
        var _a = 'Norte/Sul';
        var _b = 'Leste/Oeste';
        var _c = 'Nordeste/Sudeste/Noroeste/Sudoeste';

        var ca = p1.lat - p2.lat;
        var co = p1.lng - p2.lng;
        //console.log(ca);
        //console.log(co);
        _a = ca < 0 ? 'Norte' : 'Sul';
        _b = co < 0 ? 'Leste' : 'Oeste';
        if (ca < 0 && co < 0)
            _c = 'Nordeste';
        else if (ca < 0)
            _c = 'Noroeste';
        else if (co < 0)
            _c = 'Sudeste';
        else
            _c = 'Sudoeste';
        $('#direcoes').html(_a + ", " + _b + ' (' + _c + ')');

        ca = ca < 0 ? ca * -1 : ca;
        co = co < 0 ? co * -1 : co;

        var hip = Math.pow(ca, 2) + Math.pow(co, 2);
        hip = hip < 0 ? hip * -1 : hip;
        hip = Math.sqrt(hip);

        //console.log('ca: ' + ca + ', co: ' + co + ', hip: ' + hip);
        //var m = grau_mtr(hip);
        //console.log(m);
        addPolyline(p1, p2);
        //addPolyline(p2, { lat: p1.lat, lng: p2.lng });
        //addPolyline(p2, { lat: p2.lat, lng: p1.lng });
        //addPolyline(p1, { lat: p1.lat, lng: p2.lng });
        //addPolyline(p1, { lat: p2.lat, lng: p1.lng });
        seno = ca / hip;
        seno = Math.round(seno * 1000) / 1000;
        cosseno = co / hip;
        cosseno = Math.round(cosseno * 1000) / 1000;
        tangente = ca / co;
        tangente = Math.round(tangente * 1000) / 1000;

        //console.log('seno: ' + seno + ', cosseno: ' + cosseno + ', tangente: ' + tangente);
    }

    function getDegTan(deg) {
        var rad = deg * Math.PI / 180;
        return Math.tan(rad);
    }

    function getTanDeg(tan) {
        var rad = Math.tan(tan);
        var rad = tan * Math.PI / 180;
        return Math.tan(rad);
    }
    function FilterList(_c) {
        var _max_lat = _c.lat + dif;
        var _min_lat = _c.lat - dif;
        var _max_lng = _c.lng + dif;
        var _min_lng = _c.lng - dif;
        $(Circles).each(function (index, item) {
            var lat = item.center.lat();
            var lng = item.center.lng();
            var _b_lat = _max_lat > lat && _min_lat < lat;
            var _b_lng = _max_lng > lng && _min_lng < lng;
            var _b = _b_lat && _b_lng;
            if (_b)
                item.setOptions({ fillColor: 'blue' });
            else
                item.setOptions({ fillColor: 'red' });
            //return _b_lat && _b_lng;
        });
        //console.log(list);
    }
</script>
Seno = Cateto oposto/hipotenusa
Cosseno = Cateto adjacente/hipotenusa
Tangente = cateto oposto/cateto adjacente

GIS_APP/GIS_APP/Views/Map/Mobile.cshtml
<table class="positions">
    <tbody></tbody>
</table>

<a class="btn btn-danger" onclick="$('.positions tr').remove()" style="position: fixed; bottom: 0; right: 0;">Clear</a>
<a class="btn btn-primary" onclick="Position(lastMark.lat, lastMark.lng)" style="position: fixed; bottom: 0; left: 0;">Mark</a>
<style>
    .positions {
        width: 100%;
        font-size: 12px;
    }

        .positions td {
            border: 1px solid #000;
            padding: 0 5px;
        }
</style>
<script src="~/Content/gps_math.js"></script>
<script>
    var lastMark = { lat: -27.635424331918777, lng: -54.13765009492636 };
    $(function () {
        Connect();
    });

    mobile = (/android|webos|iphone|ipad|ipod|blackberry|iemobile|opera mini/i.test(navigator.userAgent.toLowerCase()));
    var ws;
    var url = window.location.host + "@Url.Content("~/WSHandler.ashx")";

    if (navigator.geolocation) {
        if (mobile)
            navigator.geolocation.watchPosition(geo_success, geo_error, { enableHighAccuracy: true, maximumAge: Infinity, timeout: 0 });
        else
            navigator.geolocation.getCurrentPosition(geo_success, geo_error);
    }
    //if (navigator.geolocation) {
    //setInterval(function () {
    //    navigator.geolocation.getCurrentPosition(geo_success, geo_error);
    //}, 2000);
    //}

    function geo_success(position) {
        Position(position.coords.latitude, position.coords.longitude);
    }

    function Position(latitude, longitude) {
        index = $('.positions tr').length;
        $('.positions tbody').append($('<tr><td>' + index + '</td><td>' + latitude + '</td><td>' + longitude + '</td></tr>'));

        center = { lat: latitude, lng: longitude };
        var obj = {
            position: center,
            type: 'mobile',
            points: new_point(lastMark, center),
        }
        var message = JSON.stringify(obj);
        //ws.send(message);

        $.ajax({
            type: 'POST',
            url: '@Url.Action("Position", "Map")',
            contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
            data: { message: message },
            success: function (response) {
                console.log(response);
            }, error: function (error) {
                $('.positions tbody').append($('<tr><td colspan="3">' + error.responseText + '</td></tr>'));
            }
        });
        lastMark = center;
    }
    function geo_error(error) {
        console.log(error);
        $('.positions tbody').append($('<tr><td colspan="3">' + error.message + '</td></tr>'));
    }

    function Connect() {
        try {
            ws = new WebSocket("ws://" + url);
        } catch (error) { console.log(error); }

        ws.onmessage = function (event) { console.log(event); };
        ws.onerror = function (event) { console.log(event); };
        ws.onopen = function (event) { console.log(event); };
        ws.onclose = function (event) { console.log(event); };
    }

    function new_point(p1, p2) {
        //addPolyline(p1, p2);
        lat1 = p1.lat;
        lng1 = p1.lng;
        lat2 = p2.lat;
        lng2 = p2.lng;

        brng = bearing(lat1, lng1, lat2, lng2);
        _p = points_of_square(lat1, lng1, lat2, lng2, brng, 15 / 2);
        //console.log(point);
        return { p1: _p[0], p2: _p[1], p3: _p[2], p4: _p[3] };
    }
</script>

GIS_APP/GIS_APP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
@*AIzaSyCAKNnivLnjELanRthexCyOTPwtQVEJUtw*@
<head>
    <meta charset="utf-8" />
    <title>Mapa</title>
    @*<script src="http://maps.google.com/maps/api/js" type="text/javascript"></script>*@
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?v=3&key=AIzaSyCAKNnivLnjELanRthexCyOTPwtQVEJUtw&sensor=false"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
</head>
<body>
    @RenderBody()
</body>
</html>